version: "3.8"
services:
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  backend:
    build: ./rocan_backend
    ports:
      - "8080:8080"
    volumes:
      - ./rocan_backend:/app

  frontend:
    build: ./rocan_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./rocan_frontend:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # カスタムNginx設定ファイルのマウント
      - ./nginx/error/custom_404.html:/etc/nginx/html/custom_404.html
      - ./nginx/error/custom_50x.html:/etc/nginx/html/custom_50x.html
    depends_on:
      - backend
