version: "3.8"

services:
  db:
    image: mysql:8.3
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  backend:
    build:
      context: ./rocan_backend
      target: development
      # target: production　本番用のビルド
    ports:
      - "8080:8080"
    volumes:
      - ./rocan_backend:/app
      - .air.toml:/app/.air.toml
    env_file:
      - .env
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    depends_on:
      - db

  frontend:
    build: ./rocan_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./rocan_frontend:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error/custom_404.html:/etc/nginx/html/custom_404.html
      - ./nginx/error/custom_50x.html:/etc/nginx/html/custom_50x.html
    depends_on:
      - backend

networks:
  default:
    name: my_custom_network
